### ISSUE TITLE
Verify PowMr POW-HVM5.5K-48V support

### ISSUE THREAD

**Issue by syssi** [syssi/esphome-smg-ii#22]
> Basic support for EASUN SMG II and PowMr inverters that use with RS232 WiFi dongle and SmartESS app. Select inverter type "Sumry".

https://solar-assistant.io/help/updates/changelog

@flyzet-prog

**Comment by flyzet-prog** [comment]
As soon as i get necessary hardware.

**Comment by syssi** [comment]
References: https://solaranzeige.de/phpBB3/viewtopic.php?t=2079&start=40

**Comment by syssi** [comment]
Success: [esphome-powmr.log](https://github.com/syssi/esphome-smg-ii/files/11181293/esphome-powmr.log)

**Comment by flyzet-prog** [comment]
It’s wouldn’t works without your help @syssi . Great achievement
