### ISSUE TITLE
No Values from SMG

### ISSUE THREAD

**Issue by heckmic** [syssi/esphome-smg-ii#38]
i've done the wirering exactly an checked 10 times. But i don't get any values. The ESP is shown in my iobroker mqtt with one datapoint (debug). - not more. Loggin shows only:

INFO ESPHome 2023.8.2
INFO Reading configuration /opt/iobroker/iobroker-data/esphome.0/mapawr1.yaml...
INFO Detected timezone 'Europe/Berlin'
INFO Starting log output from mapawr1/debug
INFO Connected to MQTT broker!

any idea?

ive used 3 max323 and 3 D1 minis. Same Problem

**Comment by syssi** [comment]
You was able to resolve this issue on your own, right?
