### ISSUE TITLE
Errors in the documentation

### ISSUE THREAD

**Issue by rdos314** [syssi/esphome-smg-ii#60]
I have decoded the POW-HVM5.5K-48V-P myself with the wifi-dongle, and the baudrate is wrong. It should be 9600.
In addition to that, the modbus device id can be configured in the menu, and they use big-endian byte order.

**Comment by syssi** [comment]
Where did you see a wrong baud rate?

**Comment by rdos314** [comment]
In the debugging section 2400 is listed.

**Comment by syssi** [comment]
Ouch. Thanks for pointing this out! I will push a fix.

**Comment by syssi** [comment]
Thanks for your support! Do you like to add anything else to the docs?

Could you provide some detailed instructions how to change the Modbus address via the on screen menu?
