### ISSUE TITLE
Nothing Works 

### ISSUE THREAD

**Issue by cyclemat** [syssi/esphome-smg-ii#65]
Have here an PowMR 5.5 K - P inverter try to readout the inverter have all dubble checked but all i have is this

```
er:183]: Duplicate modbus command found: type=0x3 address=420 count=1[0m
02.09.2024 10:43:00(-0 seconds) 
[0;33m[W][modbus_controller:183]: Duplicate modbus command found: type=0x3 address=406 count=1[0m
02.09.2024 10:43:00(-0 seconds) 
[0;33m[W][modbus_controller:183]: Duplicate modbus command found: type=0x3 address=331 count=7[0m
02.09.2024 10:43:00(-0 seconds) 
[0;33m[W][modbus_controller:183]: Duplicate modbus command found: type=0x3 address=329 count=1[0m
02.09.2024 10:43:00(-0 seconds) 
[0;33m[W][modbus_controller:183]: Duplicate modbus command found: type=0x3 address=323 count=5[0m
02.09.2024 10:43:00(-0 seconds) 
[0;33m[W][modbus_controller:183]: Duplicate modbus command found: type=0x3 address=320 count=2[0m
02.09.2024 10:42:59(-0.04 seconds) 
[0;33m[W][modbus_controller:183]: Duplicate modbus command found: type=0x3 address=313 count=1[0m
02.09.2024 10:42:59(-0.05 seconds) 
[0;33m[W][modbus_controller:183]: Duplicate modbus command found: type=0x3 address=201 count=17[0m
02.09.2024 10:42:50(-9.91 seconds) 
[0;33m[W][modbus_controller:183]: Duplicate modbus command found: type=0x3 address=643 count=1[0m
02.09.2024 10:42:50(-0 seconds) 
[0;33m[W][modbus_controller:183]: Duplicate modbus command found: type=0x3 address=305 count=6[0m
02.09.2024 10:42:50(-0 seconds) 
[0;33m[W][modbus_controller:183]: Duplicate modbus command found: type=0x3 address=300 count=4[0m
02.09.2024 10:42:50(-0 seconds) 
[0;33m[W][modbus_controller:183]: Duplicate modbus command found: type=0x3 address=232 count=3[0m
02.09.2024 10:42:50(-0 seconds) 
[0;33m[W][modbus_controller:183]: Duplicate modbus command found: type=0x3 address=229 count=1[0m
02.09.2024 10:42:49(-0.04 seconds) 
[0;33m[W][modbus_controller:183]: Duplicate modbus command found: type=0x3 address=223 count=5[0m
02.09.2024 10:42:49(-0.05 seconds) 
[0;33m[W][modbus_controller:183]: Duplicate modbus command found: type=0x3 address=219 count=2[0m
02.09.2024 10:42:40(-9.9 seconds) 
[0;33m[W][modbus_controller:183]: Duplicate modbus command found: type=0x3 address=420 count=1[0m
02.09.2024 10:42:40(-0 seconds) 
[0;33m[W][modbus_controller:183]: Duplicate modbus command found: type=0x3 address=406 count=1[0m
02.09.2024 10:42:40(-0 seconds) 
[0;33m[W][modbus_controller:183]: Duplicate modbus command found: type=0x3 address=331 count=7[0m
02.09.2024 10:42:40(-0 seconds) 
[0;33m[W][modbus_controller:183]: Duplicate modbus command found: type=0x3 address=329 count=1[0m
02.09.2024 10:42:40(-0 seconds) 
[0;33m[W][modbus_controller:183]: Duplicate modbus command found: type=0x3 address=323 count=5[0m
02.09.2024 10:42:40(-0 seconds) 
[0;33m[W][modbus_controller:183]: Duplicate modbus command found: type=0x3 address=320 count=2[0m
02.09.2024 10:42:39(-0.04 seconds) 
[0;33m[W][modbus_controller:183]: Duplicate modbus command found: type=0x3 address=313 count=1[0m
02.09.2024 10:42:39(-0.05 seconds) 
[0;33m[W][modbus_controller:183]: Duplicate modbus command found: type=0x3 address=108 count=2[0m
02.09.2024 10:42:30(-9.91 seconds) 
[0;33m[W][modbus_controller:183]: Duplicate modbus command found: type=0x3 address=643 count=1[0m`
```

![image](https://github.com/user-attachments/assets/105cd0ad-40fc-4904-b91c-584670186221)

can anybody help me want to controll the charging section to charge the battery when tibber price is low

**Comment by syssi** [comment]
Please increase the log level to `DEBUG` and provide another log: https://github.com/syssi/esphome-smg-ii?tab=readme-ov-file#debugging

Could you take some photos of your wiring and RS485 module? I guess your wiring isn't correct or the flow control is not properly managed.

**Comment by cyclemat** [comment]
RS485 ? in the readme stands RS232 !

Here are Pictures will set the debug level this evening ! 

![image](https://github.com/user-attachments/assets/e840df04-8a0b-4711-b548-9cf110face43)
![image](https://github.com/user-attachments/assets/67e12d98-1bb7-4063-b073-ad19a352c9f3)
![image](https://github.com/user-attachments/assets/0347a33e-09c0-4c72-9152-eb94a7877008)
![image](https://github.com/user-attachments/assets/de0a91d0-3ad2-4ab8-97a8-33a4d950da7f)

**Comment by syssi** [comment]
> RS485 ? in the readme stands RS232 !

My fault. It's RS232! :-)

**Comment by syssi** [comment]
Could you check the chip model of your RS232 converter? It's important to use the `MAX3232` (3.3V model) and no `MAX232` (5V model).

**Comment by cyclemat** [comment]
Will check but i have buy IT as 3,3v habe ordered new ones to test 

https://www.ebay.de/itm/255312120055?mkcid=16&mkevt=1&mkrid=707-127634-2357-0&ssspo=kSLcqpXwSAK&sssrc=4429486&ssuid=0HguCZJXT4u&var=&widget_ver=artemis&media=COPY

This is What is in use in the moment
 https://www.ebay.de/itm/255303534424?mkcid=16&mkevt=1&mkrid=707-127634-2357-0&ssspo=kSLcqpXwSAK&sssrc=4429486&ssuid=0HguCZJXT4u&var=&widget_ver=artemis&media=COPY

**Comment by cyclemat** [comment]
mmmmh 
![image](https://github.com/user-attachments/assets/fd14aa09-556a-4ca3-ad3e-65b328d2f414)

**Comment by cyclemat** [comment]
and is this normal in compiling ? 
![image](https://github.com/user-attachments/assets/d628b228-0042-4343-90fd-f6d99085322b)

**Comment by cyclemat** [comment]
so i have rebuild all with a new ESP and a new MAX2322 and had to need swap the RX and TX pin and now it works look mine ESP32 has a wrong pinout  thanks for help
