### ISSUE TITLE
cant write to Output priority and Battery charging priority

### ISSUE THREAD

**Issue by cyclemat** [syssi/esphome-smg-ii#69]
nos i become all datas but the problem is cant change Output priority and Battery charging priority have try to send direct via mqqt and openhab but it didnt work have try it via smg-ii/select/smg-ii_output_priority/command/ its only a me problem or has anybody the same problem ?

**Comment by syssi** [comment]
What did you send exactly? The topic is called `smg-ii/select/smg-ii_output_priority/command`. There is no trailing slash.

**Comment by cyclemat** [comment]
have send 1,2,3 nothing happens 
![image](https://github.com/user-attachments/assets/e68220d3-f858-42ea-a30f-0fa5efc74d30)

**Comment by syssi** [comment]
1. Please remove the trailing slash from the topic:

```
smg-ii/select/smg-ii_output_priority/command

vs. 

smg-ii/select/smg-ii_output_priority/command/
```

2. Select `raw` instead of `json`
3. Send a value between 0 and 3.

```
      "Utility-PV-Battery (UTI)": 0
      "PV-Utility-Battery (SOL)": 1
      "PV-Battery-Utility (SBU)": 2
      "PV-Utility-Battery (SUB)": 3
```

**Comment by cyclemat** [comment]
![image](https://github.com/user-attachments/assets/7aef6ce7-c514-4a3e-96ad-82041057b313)
![image](https://github.com/user-attachments/assets/d0900a37-e630-46c1-9d40-4bce9587b67a)
nothing happens

**Comment by syssi** [comment]
Hmm... this is new to me and probably a bug or incompatibility. If you change the `output priority` using the on screen display does the state of the number entity change? In other words: Does reading the current state of the `output priority` work and are you able to change the mode in general?

**Comment by syssi** [comment]
Could you try to transmit the label/option name instead of the integer?

```
```
$ mosquitto_pub 'smg-ii/select/smg-ii_output_priority/command' -m 0

[10:12:18][D][select:062]: 'smg-ii output priority' - Setting
[10:12:18][W][select:111]: 'smg-ii output priority' - Option 0 is not a valid option

$ mosquitto_pub -h 192.168.1.100 -u wilfried -P oc-0p1um -t 'smg-ii/select/smg-ii_output_priority/command' -m "Utility-PV-Battery (UTI)"
[10:13:10][D][select:062]: 'smg-ii output priority' - Setting
[10:13:10][D][select:115]: 'smg-ii output priority' - Set selected option to: Utility-PV-Battery (UTI)
[10:13:10][D][modbus_controller.select:048]: Found value 0 for option 'Utility-PV-Battery (UTI)'
```

**Comment by cyclemat** [comment]
have test Utility-PV-Battery (UTI) and it works
![image](https://github.com/user-attachments/assets/d3804032-6397-45c7-a168-2364b7d0bf35)

**Comment by syssi** [comment]
Could you provide a valid `maximum charging current` value of your inverter? I would like to add some examples to the YAML like:

```
# If you use `mqtt` you can control the inverter using the `command` topics. The topic depends on
# the name of your ESPHome node and the name of the entity:
#
# mosquitto_pub -t 'smg-ii/select/smg-ii_output_priority/command' -m "Utility-PV-Battery (UTI)"
# mosquitto_pub -t 'smg-ii/switch/smg-ii_energy-saving_mode/command' -m 'ON'    # Supported values: ON, OFF, TOGGLE
# mosquitto_pub -t 'smg-ii/number/smg-ii_maximum_charging_current/command' -m 10

```

**Comment by cyclemat** [comment]
its not a bug it a feature ;) thanks

**Comment by syssi** [comment]
@cyclemat Did you miss my last question?

**Comment by cyclemat** [comment]
Mmmh Max charging for Utility charging or complete ?

Utility charging from 2a up
For conplete 5a up
