### ISSUE TITLE
Support with the mqtt command needed

### ISSUE THREAD

**Issue by Schekamatik** [syssi/esphome-smg-ii#78]
Hello I am using your repository to read the data from POW-HVM5.5K-48V-P via the mqtt ../state topic and it works well so far. 
Now I would like to use my red node MQTT Server to change the configuration via the .../command topic.
As I can see for example the ../command topic is only available for 0/1 settings and it works but what about the operation mode for example?
How can I change for example the operation mode via mqtt topic request?

Sorry I am really new in the ESPhome area and currently can not find any explanation how to do it on our .yaml file.

Thank you very much in advance.

**Comment by syssi** [comment]
First of all this project isn't feature complete. `binary_sensor` and `sensor` entities are reas-only entities and cannot be changed/controlled via MQTT. At the moment you will find only `switch` and `number` entities at the configuration YAML. As you can see there is now "operation mode" control yet.

What do you miss in detail? We could try to extend the project as soon you are willing to provide some testing.

**Comment by Schekamatik** [comment]
Hello @syssi when are you approximately planning to implement this functionality?

**Comment by syssi** [comment]
@Schekamatik Are you able to talk to your inverter already? Are you able to retrieve measuerements and test new features to control your inverter? Which feature do you want to control?

**Comment by Schekamatik** [comment]
Hello @syssi yes am I able to talk to my inverter. I can read the measurements. 
 I need to change dynamically some options(Operation Mode, Output priority and Battery charging priority) of the inverter via mqtt command.
Thank you

**Comment by syssi** [comment]
- Operation Mode: The operation mode is read-only and cannot be controlled directly
- Output priority: https://github.com/syssi/esphome-smg-ii/blob/main/esp32-example.yaml#L641-L652
- Battery charging priority: https://github.com/syssi/esphome-smg-ii/blob/main/esp32-example.yaml#L689-L700

See https://github.com/syssi/esphome-smg-ii/issues/69#issuecomment-2330891197
